runtime: python312

entrypoint: gunicorn -b :$PORT main:app

handlers:
  - url: /.*
    secure: always
    script: auto

env_variables:
  APP_RUNNING_ENV: PROD
  DB_USER: root
  DB_PASS: x%npoJsENm/5b8tz 
  DB_NAME: hospital_db
  CLOUD_SQL_CONNECTION_NAME: bdcc2025-451416:europe-west1:bdcc-proj1-mysql
  BUCKET_NAME: bucket-patient-files


vpc_access_connector:
  name: projects/bdcc2025-451416/locations/europe-west1/connectors/app-sql-connector-1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50